import { Product } from "./types";

/**
 * Demo product data — used until Supabase is connected.
 * Images reference the actual product photos in /public/products/
 */
export const demoProducts: Product[] = [
    {
        id: "1",
        name_en: "Pikachu Plushie",
        slug: "pikachu-plushie",
        description_en: "A cheerful, hand-crocheted Pikachu made with premium soft yarn. Every stitch is made with love — the perfect gift for any Pokémon fan.",
        price: 850,
        compare_at_price: 1000,
        category: "plushies",
        collection: "anime",
        stock: 3,
        images: ["/products/24730378-3746-4e7f-88e5-58a5d0d49ee4.jpg", "/products/24730378-3746-4e7f-88e5-58a5d0d49ee4.jpg"],
        featured: true,
        sort_order: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "2",
        name_en: "Totoro Plushie",
        slug: "totoro-plushie",
        description_en: "Our beloved Totoro, crocheted from the softest plush yarn. A studio Ghibli fan's dream — small enough to carry, cute enough to melt hearts.",
        price: 750,
        category: "plushies",
        collection: "anime",
        stock: 5,
        images: ["/products/061538e7-af87-4aac-be03-a90b068372af.jpg"],
        featured: true,
        sort_order: 2,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "3",
        name_en: "Strawberry Cow",
        slug: "strawberry-cow",
        description_en: "The internet's favorite — a pink strawberry cow crocheted with chunky premium yarn. Irresistibly huggable.",
        price: 950,
        category: "plushies",
        collection: "animals",
        stock: 2,
        images: ["/products/836512a4-3cc2-44d6-a136-2ebe41efe0e0.jpg", "/products/836512a4-3cc2-44d6-a136-2ebe41efe0e0.jpg"],
        featured: true,
        sort_order: 3,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "4",
        name_en: "Baymax Mini",
        slug: "baymax-mini",
        description_en: "A tiny hand-crocheted Baymax with an embroidered heart. Your personal healthcare companion, pocket-sized.",
        price: 650,
        category: "plushies",
        collection: "characters",
        stock: 4,
        images: ["/products/87c4919f-60eb-473d-879c-e9dd45f5d7f8.jpg", "/products/87c4919f-60eb-473d-879c-e9dd45f5d7f8.jpg"],
        featured: true,
        sort_order: 4,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "5",
        name_en: "Blue Dolphin",
        slug: "blue-dolphin",
        description_en: "A playful blue dolphin crafted with vibrant yarn. Perfect for ocean lovers and anyone who needs a splash of joy.",
        price: 700,
        category: "plushies",
        collection: "animals",
        stock: 6,
        images: ["/products/7da9ee72-b8d6-4596-a624-461aabf72b10.jpg"],
        featured: false,
        sort_order: 5,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "6",
        name_en: "Baby Chick",
        slug: "baby-chick",
        description_en: "A palm-sized baby chick with a tiny red bow. So small, so round, so impossibly cute.",
        price: 450,
        category: "plushies",
        collection: "animals",
        stock: 8,
        images: ["/products/53ba483b-028b-43e6-b6fb-ca5e3ea41273.jpg"],
        featured: false,
        sort_order: 6,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "7",
        name_en: "Snorlax Keychain",
        slug: "snorlax-keychain",
        description_en: "A sleepy Snorlax keychain — crocheted in teal and white. Clip it to your bag and let him nap everywhere you go.",
        price: 350,
        category: "accessories",
        collection: "anime",
        stock: 10,
        images: ["/products/9e28e265-e205-4b3d-a37b-d46bddd7d772.jpg"],
        featured: true,
        sort_order: 7,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "8",
        name_en: "Pikachu Keychain",
        slug: "pikachu-keychain",
        description_en: "A mini Pikachu keychain with rosy cheeks. Handmade crochet charm for your keys, bag, or backpack.",
        price: 350,
        category: "accessories",
        collection: "anime",
        stock: 12,
        images: ["/products/0a42148a-b609-4339-a655-4c48e885e7bd.jpg", "/products/0a42148a-b609-4339-a655-4c48e885e7bd (1).jpg"],
        featured: false,
        sort_order: 8,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "9",
        name_en: "Panda Cow",
        slug: "panda-cow",
        description_en: "A unique black-and-white cow plushie with panda-like markings. A collector's piece for the truly devoted.",
        price: 900,
        category: "plushies",
        collection: "animals",
        stock: 1,
        images: ["/products/b45860ae-71d9-49af-8f89-f835dc1d9ac8.jpg"],
        featured: false,
        sort_order: 9,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "10",
        name_en: "Sailor Character",
        slug: "sailor-character",
        description_en: "A hand-crocheted sailor character with a tiny hat and scarf. Detailed, adorable, and one-of-a-kind.",
        price: 550,
        category: "plushies",
        collection: "characters",
        stock: 3,
        images: ["/products/87d281f9-80b4-44a4-b4db-073224e23451.jpg"],
        featured: false,
        sort_order: 10,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "11",
        name_en: "Baby Chick Keychain",
        slug: "baby-chick-keychain",
        description_en: "A tiny crochet chick with a red bow — clip it to your bag for instant cuteness overload.",
        price: 300,
        category: "accessories",
        collection: "animals",
        stock: 15,
        images: ["/products/2668fb56-fce4-4918-9092-43b51ab9b8ce.jpg"],
        featured: false,
        sort_order: 11,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];
